-- Generated by applycolor.sh — do not edit. Loaded by hyprland.lua (dofile, last to win).
-- Persists colors across reloads to match the live hyprctl state. Border *visibility*
-- is controlled separately (disableHyprlandBorders), so this only sets colors.
hl.config({
    ['general.col.active_border']        = { colors = {'0xffa23c43', '0xffffdad9'}, angle = 45 },
    ['general.col.inactive_border']      = '0xfff0e3e1',
    ['decoration.shadow.color']          = '0x88a23c43',
    ['decoration.shadow.color_inactive'] = '0x44000000',
    ['group.col.border_active']          = '0xffa23c43',
    ['group.col.border_inactive']        = '0xfff0e3e1',
    ['group.col.border_locked_active']   = '0xffa23c43',
    ['group.col.border_locked_inactive'] = '0xfff0e3e1',
    ['misc.background_color']            = '0xfff8f0ed',
})

hl.window_rule({
    match        = { pin = 1 },
    border_color = '0xAAa23c43 0x77a23c43',
})
