-- Hyprland Monitor Configuration
-- Auto-generated by MonitorDeck v1.1.0

hl.monitor({
    output = "DP-5",
    mode = "2560x1440@60",
    position = "7100x2160",
    scale = 1,
    transform = 0,
    bitdepth = 12,
    cm = "auto",
    sdrbrightness = 2.55,
    sdrsaturation = 0.96,
    disabled = false
})

hl.monitor({
    output = "DP-4",
    mode = "2560x1440@60",
    position = "4540x2160",
    scale = 1,
    transform = 0,
    bitdepth = 12,
    cm = "auto",
    sdrbrightness = 3.00,
    sdrsaturation = 1.00,
    disabled = false
})

hl.monitor({
    output = "HDMI-A-4",
    mode = "3840x2160@60",
    position = "5120x0",
    scale = 1,
    transform = 0,
    bitdepth = 12,
    cm = "auto",
    sdrbrightness = 1.00,
    sdrsaturation = 0.99,
    disabled = false
})
