# ######## Custom Window Rules ########

# Terminal Effects
windowrule = match:class ^(kitty)$, opacity 0.95
windowrule = match:class ^(kitty)$, no_blur off
windowrule = match:class ^(kitty)$, xray on

# Additional Utilities to float
windowrule = match:class ^(blueman-manager|polkit-gnome-authentication-agent-1|org.gnome.polkit|lxpolkit)$, float on
windowrule = match:class ^(blueman-manager|polkit-gnome-authentication-agent-1|org.gnome.polkit|lxpolkit)$, center on
windowrule = match:class ^(blueman-manager|polkit-gnome-authentication-agent-1|org.gnome.polkit|lxpolkit)$, no_blur off
windowrule = match:class ^(blueman-manager)$, size 800 500

# Media & Graphics Workspaces
windowrule = match:class ^(Spotify)$, workspace 8
windowrule = match:class ^(Gimp-2.10)$, workspace 9

# Media Players (Float & Center)
windowrule = match:class ^(mpv|imv|vlc)$, float on
windowrule = match:class ^(mpv|imv|vlc)$, center on

# Steam sub-windows
windowrule = match:class ^(steam)$, match:title ^(Friends List|Steam - News|Settings|Steam Settings|.* - Chat|.* - Shop)$, float on
windowrule = match:class ^(steam)$, match:title ^(Friends List|Steam - News|Settings|Steam Settings|.* - Chat|.* - Shop)$, center on

# Theme Utilities & System Tools
windowrule = match:class ^(nwg-look|qt5ct|qt6ct|kvantummanager)$, float on
windowrule = match:class ^(nwg-look|qt5ct|qt6ct|kvantummanager)$, center on
windowrule = match:class ^(qalculate-gtk)$, float on
windowrule = match:class ^(qalculate-gtk)$, center on

# Center all floating windows by default
windowrule = match:float 1, center on
