$primary = rgb(00f0ff)
$surface = rgb(0a0a14)
$secondary = rgb(ff00aa)
$error = rgb(ff0040)
$tertiary = rgb(b967ff)
$surface_lowest = rgb(12121e)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
