$primary = rgb(6c782e)
$surface = rgb(f2e5bc)
$secondary = rgb(c35e0a)
$error = rgb(c14a4a)
$tertiary = rgb(4c7a5d)
$surface_lowest = rgb(f0e3ba)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
