animations {
    enabled = true

    bezier = cinIn,      0.0,  0.0,  0.2,  1.0    # slow start, dramatic decel
    bezier = cinOut,     0.8,  0.0,  1.0,  1.0    # hard exit
    bezier = cinCross,   0.4,  0.0,  0.6,  1.0    # symmetric crossfade
    bezier = menu_decel, 0.1,  1.0,  0.0,  1.0
    bezier = menu_accel, 0.38, 0.04, 1.0,  0.07
    bezier = easeInOutCirc, 0.85, 0.0, 0.15, 1.0

    animation = windows,       1, 8,   cinIn,   slide bottom
    animation = windowsIn,     1, 8,   cinIn,   slide bottom
    animation = windowsOut,    1, 5,   cinOut,  slide top
    animation = windowsMove,   1, 7,   cinIn,   slide

    animation = fade,          1, 7,   cinCross
    animation = fadeIn,        1, 7,   cinCross
    animation = fadeOut,       1, 5,   cinOut
    animation = fadeDim,       1, 7,   cinCross
    animation = fadeShadow,    1, 7,   cinCross
    animation = fadeLayersIn,  1, 6,   cinIn
    animation = fadeLayersOut, 1, 4,   cinOut

    animation = layersIn,      1, 6,   menu_decel, slide
    animation = layersOut,     1, 4,   menu_accel

    animation = border,        1, 10,  default

    animation = workspaces,       1, 10, easeInOutCirc, slidefadevert 25%
    animation = specialWorkspace, 1, 8,  cinIn,         slidefadevert 30%
}
