-- diablo-2.lua — Diablo-style popin animations (variant 2)

hl.curve("default",  { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.curve("wind",     { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.curve("overshot", { type = "bezier", points = { { 0.13, 0.99 }, { 0.29, 1.08 } } })
hl.curve("liner",    { type = "bezier", points = { { 1, 1 }, { 1, 1 } } })

hl.animation({ leaf = "windows",      enabled = true, speed = 7,  bezier = "wind",     style = "popin" })
hl.animation({ leaf = "windowsIn",    enabled = true, speed = 7,  bezier = "overshot", style = "popin" })
hl.animation({ leaf = "windowsOut",   enabled = true, speed = 5,  bezier = "overshot", style = "popin" })
hl.animation({ leaf = "windowsMove",  enabled = true, speed = 6,  bezier = "overshot", style = "slide" })
hl.animation({ leaf = "layers",       enabled = true, speed = 5,  bezier = "default",  style = "popin" })
hl.animation({ leaf = "fadeIn",       enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "fadeOut",      enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "fadeSwitch",   enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "fadeShadow",   enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "fadeDim",      enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "fadeLayers",   enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "workspaces",   enabled = true, speed = 7,  bezier = "overshot", style = "slidevert" })
hl.animation({ leaf = "border",       enabled = true, speed = 1,  bezier = "liner" })
hl.animation({ leaf = "borderangle",  enabled = true, speed = 30, bezier = "liner", style = "loop" })
