animations {
    enabled = true

    bezier = bigShot,    0.05, 0.9,  0.1,  1.15   # strong overshoot
    bezier = bigShotIn,  0.1,  1.2,  0.1,  0.9    # overshoot and bounce
    bezier = quickExit,  0.3,  0.0,  0.9,  0.1
    bezier = menu_decel, 0.1,  1.0,  0.0,  1.0
    bezier = menu_accel, 0.38, 0.04, 1.0,  0.07
    bezier = liner,      1,    1,    1,    1

    animation = windows,       1, 6,   bigShot,   slide
    animation = windowsIn,     1, 6,   bigShotIn, popin 40%
    animation = windowsOut,    1, 3,   quickExit, popin 90%
    animation = windowsMove,   1, 6,   bigShot,   slide

    animation = fade,          1, 5,   bigShot
    animation = fadeIn,        1, 5,   bigShot
    animation = fadeOut,       1, 3,   quickExit
    animation = fadeDim,       1, 5,   bigShot
    animation = fadeShadow,    1, 5,   bigShot
    animation = fadeLayersIn,  1, 4,   menu_decel
    animation = fadeLayersOut, 1, 2,   menu_accel

    animation = layersIn,      1, 5,   bigShot,   slide
    animation = layersOut,     1, 2,   menu_accel

    animation = border,        1, 1,   liner
    animation = borderangle,   1, 30,  liner, loop

    animation = workspaces,       1, 7, bigShot,   slide
    animation = specialWorkspace, 1, 6, bigShotIn, slidevert
}
