animations {
    enabled = true

    bezier = retro,     0.0,  1.0,  0.6,  1.0    # fast to start, linear settle
    bezier = retroOut,  0.6,  0.0,  1.0,  0.0    # hard out
    bezier = liner,     1,    1,    1,    1

    animation = windows,       1, 4,   retro,    popin 70%
    animation = windowsIn,     1, 4,   retro,    popin 70%
    animation = windowsOut,    1, 2,   retroOut, popin 90%
    animation = windowsMove,   1, 4,   retro,    slide

    animation = fade,          1, 3,   retro
    animation = fadeIn,        1, 3,   retro
    animation = fadeOut,       1, 2,   retroOut
    animation = fadeDim,       1, 3,   retro
    animation = fadeShadow,    1, 3,   retro
    animation = fadeLayersIn,  1, 2,   retro
    animation = fadeLayersOut, 1, 1.5, retroOut

    animation = layersIn,      1, 3,   retro,   slide
    animation = layersOut,     1, 2,   retroOut

    animation = border,        1, 1,   liner
    animation = borderangle,   1, 30,  liner, once

    animation = workspaces,       1, 5, retro,    slide
    animation = specialWorkspace, 1, 4, retro,    slidevert
}
