-- Hyprland Monitor Configuration
-- Auto-generated by MonitorPopup

hl.monitor({
    output = "HDMI-A-1",
    mode = "3840x2160@60",
    position = "3840x0",
    scale = 1,
    bitdepth = 8,
    cm = "auto",
    sdrbrightness = 1.00,
    sdrsaturation = 0.99,
    disabled = false
})

hl.monitor({
    output = "DP-1",
    mode = "3840x2160@60",
    position = "3840x2160",
    scale = 1,
    bitdepth = 8,
    cm = "auto",
    sdrbrightness = 0.99,
    sdrsaturation = 0.96,
    disabled = false
})

hl.monitor({
    output = "DP-2",
    mode = "3840x2160@60",
    position = "0x2160",
    scale = 1,
    bitdepth = 8,
    cm = "auto",
    sdrbrightness = 1.00,
    sdrsaturation = 1.00,
    disabled = false
})
