-- Hyprland Monitor Configuration
-- Auto-generated by MonitorPopup

hl.monitor({
    output = "HDMI-A-1",
    mode = "3840x2160@60",
    position = "3840x0",
    scale = 1,
    bitdepth = 10,
    cm = "adobe",
    sdrbrightness = 1.00,
    sdrsaturation = 1.00,
    disabled = false
})

hl.monitor({
    output = "DP-1",
    mode = "3840x2160@60",
    position = "3840x2160",
    scale = 1,
    bitdepth = 10,
    cm = "hdr",
    sdrbrightness = 2.50,
    sdrsaturation = 0.98,
    disabled = false
})

hl.monitor({
    output = "DP-2",
    mode = "3840x2160@60",
    position = "0x2160",
    scale = 1,
    bitdepth = 10,
    cm = "hdr",
    sdrbrightness = 3.00,
    sdrsaturation = 1.00,
    disabled = false
})
