-- Generated by applycolor.sh — do not edit. Loaded by hyprland.lua (dofile, last to win).
-- Persists colors across reloads to match the live hyprctl state. Border *visibility*
-- is controlled separately (disableHyprlandBorders), so this only sets colors.
hl.config({
    ['general.col.active_border']        = { colors = {'0xff8F6B6E', '0xff371D20'}, angle = 45 },
    ['general.col.inactive_border']      = '0xffF0DEDF',
    ['decoration.shadow.color']          = '0x888F6B6E',
    ['decoration.shadow.color_inactive'] = '0x44000000',
    ['group.col.border_active']          = '0xff8F6B6E',
    ['group.col.border_inactive']        = '0xffF0DEDF',
    ['group.col.border_locked_active']   = '0xff8F6B6E',
    ['group.col.border_locked_inactive'] = '0xffF0DEDF',
    ['misc.background_color']            = '0xffFFF8F7',
})

hl.window_rule({
    match        = { pin = 1 },
    border_color = '0xAA8F6B6E 0x778F6B6E',
})
