#!/usr/bin/env python3
import json, sys

def parse(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))

def hexof(rgb):
    return "#%02x%02x%02x" % tuple(max(0, min(255, round(c))) for c in rgb)

def mix(a, b, t):
    ca, cb = parse(a), parse(b)
    return hexof(tuple(ca[i] * (1 - t) + cb[i] * t for i in range(3)))

def alpha(h, a):
    return h + "%02x" % max(0, min(255, round(a * 255)))

src, dst = sys.argv[1], sys.argv[2]
c = json.load(open(src))

def g(*keys, default="#000000"):
    for k in keys:
        if k in c and isinstance(c[k], str) and c[k].startswith("#"):
            return c[k]
    return default

bg = g("background", "surface", default="#141313")
r, gr, b = parse(bg)
dark = (r + gr + b) / 3 < 128

# shell accent: colPrimary = mix(primary, mauve, 0.4) — not raw primary
primary = g("primary")
accent = mix(primary, "#cba6f7" if dark else "#8839ef", 0.4)

surface = g("surface", "background")
s_lowest = g("surface_container_lowest", default=mix(surface, "#000000", 0.25 if dark else 0.0))
s_low = g("surface_container_low", default=mix(surface, "#ffffff" if dark else "#000000", 0.04))
s_c = g("surface_container", default=mix(surface, "#ffffff" if dark else "#000000", 0.07))
s_high = g("surface_container_high", default=mix(surface, "#ffffff" if dark else "#000000", 0.11))
s_highest = g("surface_container_highest", default=mix(surface, "#ffffff" if dark else "#000000", 0.15))
on_surface = g("on_surface", default="#e6e1e1")
on_surface_variant = g("on_surface_variant", "subtext0", default=on_surface)
outline = g("outline", default=on_surface_variant)
outline_variant = g("outline_variant", default=outline)
on_primary = g("on_primary", default="#ffffff")
primary_container = g("primary_container", default=accent)
on_primary_container = g("on_primary_container", default=on_surface)
secondary_container = g("secondary_container", default=s_c)
on_secondary_container = g("on_secondary_container", default=on_surface)
tertiary = g("tertiary", default=accent)
error = g("error", "red", default="#ffb4ab")
inverse_surface = g("inverse_surface", default=on_surface)
inverse_on_surface = g("inverse_on_surface", default=surface)
scrim = g("scrim", default="#000000")

accent_hover = mix(accent, on_surface, 0.12)
mention_bg = alpha(accent, 0.28)
glass = alpha(s_high, 0.80)

css = f"""/**
 * @name Midnight M3
 * @author donnie + Claude
 * @version 3.0.0
 * @description Material 3 Discord theme generated from the ii shell's live scheme
 * (~/.local/state/quickshell/user/generated/colors.json). Tracks whatever theme is
 * active — custom or wallpaper. Mauve-tinted accent, layered surfaces, shell rounding,
 * frosted panels, RuneScape system font. Regenerated by applycolor.sh, NOT matugen.
 * @source https://localhost
 */

:root {{
  --md-background: {bg};
  --md-surface: {surface};
  --md-surface-c-lowest: {s_lowest};
  --md-surface-c-low: {s_low};
  --md-surface-c: {s_c};
  --md-surface-c-high: {s_high};
  --md-surface-c-highest: {s_highest};
  --md-on-surface: {on_surface};
  --md-on-surface-variant: {on_surface_variant};
  --md-outline: {outline};
  --md-outline-variant: {outline_variant};
  --md-inverse-surface: {inverse_surface};
  --md-inverse-on-surface: {inverse_on_surface};

  --md-primary: {primary};
  --md-on-primary: {on_primary};
  --md-primary-container: {primary_container};
  --md-on-primary-container: {on_primary_container};
  --md-secondary-container: {secondary_container};
  --md-on-secondary-container: {on_secondary_container};
  --md-tertiary: {tertiary};
  --md-error: {error};

  /* shell accent: colPrimary = mix(primary, mauve, 0.4) */
  --md-accent: {accent};
  --md-accent-hover: {accent_hover};

  --md-state-hover: {alpha(on_surface, 0.08)};
  --md-state-focus: {alpha(on_surface, 0.12)};
  --md-state-press: {alpha(on_surface, 0.16)};
  --md-scrim: {alpha(scrim, 0.6)};
  --md-glass: {glass};
  --md-blur: 24px;
}}

/* ───────── system font ───────── */
:root {{
  --font-primary: "RuneScape Plain 12";
  --font-display: "RuneScape Plain 12";
  --font-headline: "RuneScape Bold 12";
  --font-code: "Noto Sans Mono", monospace;
}}

body, button, input, textarea, select,
[class*="title_"], [class*="name_"], [class*="content_"], [class*="message_"] {{
  font-family: "RuneScape Plain 12", "Noto Sans", sans-serif !important;
}}
h1, h2, h3, [class*="header_"] [class*="title"], [class*="defaultColor"] strong, strong {{
  font-family: "RuneScape Bold 12", "RuneScape Plain 12", sans-serif !important;
}}
code, pre, [class*="hljs"], [class*="markup_"] code {{
  font-family: "Noto Sans Mono", monospace !important;
}}

/* ───────── rounding — matched to shell Appearance.qml ───────── */
:root {{
  --radius-xs: 8px;
  --radius-sm: 12px;
  --radius-md: 17px;
  --radius-lg: 23px;
  --radius-xl: 30px;
  --radius-window: 18px;
  --radius-round: 9999px;
}}

/* ───────── color mapping → Discord ───────── */
.theme-light, .theme-dark, :root {{
  --background-primary: var(--md-surface);
  --background-secondary: var(--md-surface-c-low);
  --background-secondary-alt: var(--md-surface-c);
  --background-tertiary: var(--md-surface-c-lowest);
  --background-floating: var(--md-surface-c-high);
  --background-nested-floating: var(--md-surface-c-high);
  --background-accent: var(--md-accent);
  --background-mobile-primary: var(--md-surface);
  --background-mobile-secondary: var(--md-surface-c-low);
  --channeltextarea-background: var(--md-surface-c-highest);
  --background-message-hover: var(--md-state-hover);

  --bg-base-primary: var(--md-surface);
  --bg-base-secondary: var(--md-surface-c-low);
  --bg-base-tertiary: var(--md-surface-c-lowest);
  --bg-surface-overlay: var(--md-surface-c-high);
  --bg-surface-raised: var(--md-surface-c);
  --bg-mod-faint: var(--md-state-hover);
  --bg-mod-subtle: var(--md-state-hover);
  --bg-mod-strong: var(--md-state-focus);
  --bg-mod-stronger: var(--md-state-press);

  --background-modifier-hover: var(--md-state-hover);
  --background-modifier-active: var(--md-state-press);
  --background-modifier-selected: var(--md-state-focus);
  --background-modifier-accent: var(--md-outline-variant);

  --brand-experiment: var(--md-accent);
  --brand-experiment-560: var(--md-accent);
  --brand-experiment-600: var(--md-accent);
  --brand-500: var(--md-accent);
  --brand-560: var(--md-accent);
  --button-filled-brand-background: var(--md-accent);
  --button-filled-brand-background-hover: var(--md-accent-hover);
  --button-filled-brand-text: var(--md-on-primary);
  --mention-foreground: var(--md-on-primary-container);
  --mention-background: {mention_bg};

  --text-normal: var(--md-on-surface);
  --text-default: var(--md-on-surface);
  --text-muted: var(--md-on-surface-variant);
  --text-secondary: var(--md-on-surface-variant);
  --header-primary: var(--md-on-surface);
  --header-secondary: var(--md-on-surface-variant);
  --channels-default: var(--md-on-surface-variant);
  --interactive-normal: var(--md-on-surface-variant);
  --interactive-hover: var(--md-on-surface);
  --interactive-active: var(--md-on-surface);
  --interactive-muted: var(--md-outline);
  --text-link: var(--md-accent);
  --text-brand: var(--md-accent);

  --scrollbar-thin-thumb: var(--md-outline-variant);
  --scrollbar-auto-thumb: var(--md-outline-variant);
  --scrollbar-auto-track: transparent;
  --input-background: var(--md-surface-c-highest);
  --deprecated-card-bg: var(--md-surface-c);
  --modal-background: var(--md-surface-c-low);
  --modal-footer-background: var(--md-surface-c);
}}

/* ───────── structural M3 touches ───────── */
[class*="link_"][class*="selected"],
[class*="link_"]:hover,
[class*="channel_"][aria-selected="true"] [class*="link_"] {{ border-radius: var(--radius-md) !important; }}
[class*="channel_"] [aria-selected="true"] {{ background: var(--md-secondary-container) !important; }}

[class*="numberBadge_"], [class*="mentionsBar_"], [class*="pill_"], [class*="unread_"] {{
  border-radius: var(--radius-round) !important;
}}
button[class*="button_"]:not([class*="lookBlank"]) {{ border-radius: var(--radius-round) !important; }}

[class*="channelTextArea_"] [class*="scrollableContainer_"],
[class*="channelTextArea_"] form {{
  border-radius: var(--radius-xl) !important;
  border: none !important;
  background: var(--md-surface-c-highest) !important;
}}

[class*="card_"], [class*="modal_"], [class*="root_"][class*="popout"],
[class*="layer_"] [class*="container_"] {{ border-radius: var(--radius-lg) !important; }}

/* frosted floating panels — signature ii glass-over-content */
[class*="root_"][class*="popout"], [class*="menu_"], [class*="autocomplete_"],
[class*="emojiPicker"], [class*="stickerPicker"], [class*="contextMenu"] {{
  background: var(--md-glass) !important;
  backdrop-filter: blur(var(--md-blur)) saturate(1.1) !important;
  -webkit-backdrop-filter: blur(var(--md-blur)) saturate(1.1) !important;
  border: 1px solid var(--md-outline-variant) !important;
  border-radius: var(--radius-lg) !important;
}}

[class*="listItem_"] [class*="wrapper_"] {{
  border-radius: var(--radius-lg) !important;
  transition: border-radius .2s ease !important;
}}
[class*="listItem_"] [class*="wrapper_"]:hover,
[class*="selected"] [class*="wrapper_"] {{ border-radius: var(--radius-md) !important; }}

[class*="divider_"], [class*="scroller_"] [class*="container_"] hr {{
  border-color: var(--md-outline-variant) !important;
  opacity: .5;
}}

[class*="tooltip_"] {{
  background: var(--md-inverse-surface) !important;
  color: var(--md-inverse-on-surface) !important;
  border-radius: var(--radius-sm) !important;
}}

::-webkit-scrollbar {{ width: 8px !important; height: 8px !important; }}
::-webkit-scrollbar-thumb {{
  background: var(--md-outline-variant) !important;
  border-radius: var(--radius-round) !important;
  border: 2px solid transparent !important;
  background-clip: padding-box !important;
}}
::-webkit-scrollbar-thumb:hover {{ background: var(--md-outline) !important; }}
::-webkit-scrollbar-track {{ background: transparent !important; }}
"""

open(dst, "w").write(css)
print(f"[discord] wrote {dst} ({'dark' if dark else 'light'}, accent {accent})")
