color0 #0f1e2e
color1 #fd4663
color2 #67a6e4
color3 #5c5cd6
color4 #9966cc
color5 #93c0ec
color6 #9696e9
color7 #f2f2f3
color8 #5f6974
color9 #fd4663
color10 #67a6e4
color11 #5c5cd6
color12 #9966cc
color13 #93c0ec
color14 #9696e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #0f1e2e
background            #0f1e2e
foreground            #f2f2f3
selection_foreground  #afb2b6
selection_background  #14293d
active_border_color   #67a6e4
inactive_border_color #14293d
url_color             #67a6e4

active_tab_foreground   #12171b
active_tab_background   #67a6e4
inactive_tab_foreground #afb2b6
inactive_tab_background #14293d
cursor_trail_color      #afb2b6
