color0 #0e141b
color1 #e14c4c
color2 #a4d007
color3 #d4ac0d
color4 #417a9b
color5 #9d6dff
color6 #66c0f4
color7 #8f98a0
color8 #2a475e
color9 #ff6b6b
color10 #c2e337
color11 #f0d264
color12 #66c0f4
color13 #b794ff
color14 #8ed8ff
color15 #c6d4df

cursor                #66c0f4
cursor_text_color     #0a0e14
background            #0e141b
foreground            #c6d4df
selection_foreground  #c6d4df
selection_background  #2a475e
active_border_color   #66c0f4
inactive_border_color #1b2838
url_color             #66c0f4

active_tab_foreground   #0a0e14
active_tab_background   #66c0f4
inactive_tab_foreground #8f98a0
inactive_tab_background #1b2838
cursor_trail_color      #8f98a0
