color0 #0e1b30
color1 #fd4663
color2 #6797e4
color3 #6a5cd6
color4 #a661d1
color5 #93b5ec
color6 #9f96e9
color7 #f2f2f3
color8 #5e6773
color9 #fd4663
color10 #6797e4
color11 #6a5cd6
color12 #a661d1
color13 #93b5ec
color14 #9f96e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #0e1b30
background            #0e1b30
foreground            #f2f2f3
selection_foreground  #afb2b6
selection_background  #12243f
active_border_color   #6797e4
inactive_border_color #12243f
url_color             #6797e4

active_tab_foreground   #020304
active_tab_background   #6797e4
inactive_tab_foreground #afb2b6
inactive_tab_background #12243f
cursor_trail_color      #afb2b6
